# Generated by Django 5.2 on 2026-05-03 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('classic_milk_tea', '🧊 Classic Milk Tea'), ('premium_milk_tea', '⭐ Premium Milk Tea'), ('milkshakes', '🥤 Milkshakes'), ('special_milkshakes', '🌟 Special Milkshakes'), ('sundaes', '🍨 Sundaes'), ('floats', '🥤 Floats'), ('fruit_soda', '🍹 Fruit Soda with Nata'), ('iced_coffee', '☕ Iced Coffee'), ('burgers', '🍔 Burgers'), ('fries', '🍟 Fries'), ('rice_meals', '🍚 Rice Meals'), ('siopao', '🥟 Siopao')], max_length=20)),
                ('price_16oz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price_22oz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price_12oz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price_single', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('stock', models.IntegerField(default=999)),
                ('low_stock_alert', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField()),
                ('last_restock', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='tea_shop.product')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('12oz', '12oz'), ('16oz', '16oz'), ('22oz', '22oz'), ('solo', 'Solo'), ('duo', 'Duo'), ('group', 'Group'), ('small', 'Small'), ('big', 'Big'), ('regular', 'Regular'), ('special', 'Special'), ('premium', 'Premium'), ('single', 'Single')], max_length=10, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tea_shop.product')),
            ],
        ),
    ]
