# Generated by Django 5.2 on 2026-05-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('classic_milk_tea', '🧊 Classic Milk Tea'), ('premium_milk_tea', '⭐ Premium Milk Tea'), ('milkshakes', '🥤 Milkshakes'), ('special_milkshakes', '🌟 Special Milkshakes'), ('sundaes', '🍨 Sundaes'), ('floats', '🥤 Floats'), ('fruit_soda', '🍹 Fruit Soda with Nata'), ('fruit_soda_floats', '🍹 Fruit Soda Floats'), ('ice_cream', '🍦 Ice Cream'), ('iced_coffee', '☕ Iced Coffee'), ('burgers', '🍔 Burgers'), ('fries', '🍟 Fries'), ('rice_meals', '🍚 Rice Meals'), ('siopao', '🥟 Siopao')], max_length=20),
        ),
    ]
